language: python

python:
  - 3.7.2

env:
  - DJANGO="Django==2.1.5"

matrix:
  exclude:
    # Python 3.4 is not supported in Django before 1.7.
    - env: DJANGO="Django==2.1.5"
      python: 3.7.2

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py test drf_boilerplate
  - coverage run --source=drf_boilerplate manage.py test drf_boilerplate

after_success:
  - coveralls
